spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 752010344595-04dnf1flte9ilukt7om1mqlngkfd55vf.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/google/loginGG
            authorization-grant-type: authorization_code
            scope:
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/userinfo.email
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo


server:
  port: 8080


jwt:
  signerKey: "pVPA1FNshXJpuMg77OZuP3Z0HcmM3ot0H1vXlTV2c3qFJ6bl8QVDvDx4rXDXklh1"
  valid-duration: 360000 # in second